### PR TITLE
Cloudwatch setup

### PR DESCRIPTION
**Pull request by katelynzzz**

### CODE REVIEW

**Comment by htransteven** [comment]
image

**Comment by katelynzzz** [comment]
so far the only appointment id that works is 1000000 since that is the only one that has data so plz use that for testing for now

**Review by htransteven — APPROVED** [review]
Need to fix the merge conflict. If you test it and it works afterwards, feel free to merge.

**Comment by katelynzzz** [comment]
now using appt_id = 1719619 to test

**Pull request merged**
